branches:
  only:
    - develop
    - main
    - /.*/travisci_.*$/

dist: focal
arch: arm64

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - |
    pip install -e .

script:
  - pytest